services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_USER: postgres
      POSTGRES_DB: skytraverse
    ports:
      - '5580:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:latest
    ports:
      - '5581:8080'
    restart: always
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/skytraverse
      HASURA_GRAPHQL_ENABLE_CONSOLE: false
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_AUTH_HOOK: http://localhost:3000/api/auth/authorize-request
      HASURA_GRAPHQL_AUTH_HOOK_MODE: POST

volumes:
  postgres:
