services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_USER: postgres
      POSTGRES_DB: skytraversedb
    ports:
      - '5590:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:latest
    ports:
      - '5591:8080'
    restart: always
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/skytraversedb
      HASURA_GRAPHQL_ENABLE_CONSOLE: false
      HASURA_GRAPHQL_ADMIN_SECRET: 1234

volumes:
  postgres:
